CREATE TABLE IF NOT EXISTS app_groups (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(40) NOT NULL UNIQUE,
    description TEXT DEFAULT NULL,
    short_description VARCHAR(250) DEFAULT NULL,
    image VARCHAR(250) DEFAULT NULL,
    url VARCHAR(250) DEFAULT NULL,
    is_private TINYINT NOT NULL,
    settings TEXT DEFAULT NULL,
    created_at DATE NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
